[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_deps = adafruit/Adafruit NeoPixel
            arduinogetstarted/ezButton

; デフォルトで設定されやすい最適化フラグを無効化
build_unflags = -Os -O1 -O2
; O3 最適化を明示的に指定
build_flags = -O3


